# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Manuel O. Guevara"
resume_title:                   "Pedagogía de las Ciencias Experimentales Informática"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "manuel.guevara@unach.edu.ec"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+593 98 990 6448"
resume_contact_address:         "10 de Agosto & Cuba"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>
Hola, mi nombre es Manuel y tengo 22 años. 
Soy una persona con muchas virtudes, entre ellas destaco mi capacidad de trabajo en equipo, mi perseverancia para alcanzar mis metas y mi empatía hacia los demás.
Me considero una persona proactiva y con una actitud positiva ante los desafíos que se presentan en mi vida.
En cuanto a mis intereses, me gusta mucho el deporte. Practico regularmente Taekwondo y Fútbol, lo cual me ayuda a mantenerme en forma y a liberar el estrés del día a día. 
El deporte también me ha enseñado valores como el respeto, la disciplina y la superación personal. </p>"
# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/oswa33"
  resume_twitter_url:           "https://twitter.com/ManuelG79753478?t=Co8zFwiSOLekPTxSBaWWxQ&s=09"
  resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/oswaldo.guevara.54738?mibextid=ZbWKwL"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  resume_instagram_url:         "https://www.instagram.com/manuel_oswaldo00/"
  resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
